### ISSUE TITLE
Mac zip installer fails

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#556]
Executing `./install.sh /tmp` fails with following error:
```
Installing gauge at /tmp
Creating /tmp if it doesn't exist
Copying files to /tmp
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

### Fix

We could use below command to find last modified time of `gauge.properties` file.
```
stat -f "%m"  share/gauge/gauge.properties
```

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 10-03-2017.

**Comment by sguptatw** [comment]
the format to be used is
`GAUGE_PREFIX=/tmp ./install.sh`

**Comment by sguptatw** [comment]
Getting the following error
Creating /home/sswaroop/.gauge/config ...
mkdir: cannot create directory ‘/home/sswaroop/.gauge’: Permission denied

**Comment by BugDiver** [comment]
should be fixed as part of getgauge/gauge-test#15.

**Comment by sguptatw** [comment]
This issue is still replicable.

**Comment by sguptatw** [comment]
installed using the pkg first. Then I used the zip file to install and then got the error
```
Installed gauge binaries at /tmp
If you have Gauge installed already and there are any manual changes in gauge.properties file, a backup of it has been taken at HOME/.gauge/config/gauge.properties.bak. You can restore these configurations later.
./install.sh: line 176: /Users/sswaroop/.gauge/config/timestamp.txt: Permission denied
```

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 17-03-2017.

**Comment by sguptatw** [comment]
The issue is still replicable with installer gauge-0.8.2.nightly-2017-03-17-darwin.x86_64.zip
